name: Deploy to Github Pages
on:
  push:
    branches:
      - main
  workflow-dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run shell script
        run: |
          bash build.sh
      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}